"""Add Friend, MuteStatus, BlockStatus tables

Revision ID: 6d3ba875ae54
Revises: b8ad1d2e0df5
Create Date: 2025-06-28 15:40:04.428841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d3ba875ae54'
down_revision: Union[str, None] = 'b8ad1d2e0df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('block_status_user_id_fkey', 'block_status', type_='foreignkey')
    op.drop_constraint('block_status_blocked_user_id_fkey', 'block_status', type_='foreignkey')
    op.create_foreign_key(None, 'block_status', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'block_status', 'users', ['blocked_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('friends_friend_id_fkey', 'friends', type_='foreignkey')
    op.drop_constraint('friends_user_id_fkey', 'friends', type_='foreignkey')
    op.create_foreign_key(None, 'friends', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'friends', 'users', ['friend_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('messages_receiver_id_fkey', 'messages', type_='foreignkey')
    op.drop_constraint('messages_sender_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('mute_status_user_id_fkey', 'mute_status', type_='foreignkey')
    op.drop_constraint('mute_status_muted_user_id_fkey', 'mute_status', type_='foreignkey')
    op.create_foreign_key(None, 'mute_status', 'users', ['muted_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'mute_status', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mute_status', type_='foreignkey')
    op.drop_constraint(None, 'mute_status', type_='foreignkey')
    op.create_foreign_key('mute_status_muted_user_id_fkey', 'mute_status', 'users', ['muted_user_id'], ['id'])
    op.create_foreign_key('mute_status_user_id_fkey', 'mute_status', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_sender_id_fkey', 'messages', 'users', ['sender_id'], ['id'])
    op.create_foreign_key('messages_receiver_id_fkey', 'messages', 'users', ['receiver_id'], ['id'])
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.drop_constraint(None, 'friends', type_='foreignkey')
    op.create_foreign_key('friends_user_id_fkey', 'friends', 'users', ['user_id'], ['id'])
    op.create_foreign_key('friends_friend_id_fkey', 'friends', 'users', ['friend_id'], ['id'])
    op.drop_constraint(None, 'block_status', type_='foreignkey')
    op.drop_constraint(None, 'block_status', type_='foreignkey')
    op.create_foreign_key('block_status_blocked_user_id_fkey', 'block_status', 'users', ['blocked_user_id'], ['id'])
    op.create_foreign_key('block_status_user_id_fkey', 'block_status', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
