"""Add is_online field to User

Revision ID: 700612d4d2f7
Revises: ff07c3a7fdb3
Create Date: 2025-05-04 22:15:12.484504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '700612d4d2f7'
down_revision: Union[str, None] = 'ff07c3a7fdb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
