"""Add message visibility columns

Revision ID: 97c44f6a3af5
Revises: 6d3ba875ae54
Create Date: 2025-06-30 17:53:44.348300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c44f6a3af5'
down_revision: Union[str, None] = '6d3ba875ae54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('visible_to_sender', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('visible_to_receiver', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'visible_to_receiver')
    op.drop_column('messages', 'visible_to_sender')
    # ### end Alembic commands ###
