"""Update user online status field

Revision ID: bd63fe1eee55
Revises: e8681953540b
Create Date: 2025-05-04 22:09:24.655234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd63fe1eee55'
down_revision: Union[str, None] = 'e8681953540b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_online',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
